export const mockUser = {
  id: "u_001",
  name: "Kennedy Ayuk",
  email: "kennedy.ayuk@example.com",
  initials: "KA",
  joinDate: "January 2024",
  language: "English",
  avatar: null,
  stats: {
    total: 247,
    text: 189,
    speech: 58,
    thisWeek: 34,
  },
};

export const mockHistory = [
  {
    id: "h_001",
    source: "Hello, how are you doing today?",
    target: "Ɛyo̧, o̧ ndɛ mɛ wɔ nyɔŋ yɛ?",
    direction: "EN → KY",
    date: "2026-06-21",
    time: "14:32",
    type: "text" as const,
  },
  {
    id: "h_002",
    source: "Mbok bɛ̀sə mɛ tɛ̀mɛ yɛ.",
    target: "Please help me find the way.",
    direction: "KY → EN",
    date: "2026-06-21",
    time: "13:15",
    type: "text" as const,
  },
  {
    id: "h_003",
    source: "Good morning, welcome to our village.",
    target: "Mbɛ̀ wɔ nyɔŋ, ɛ̀kɛ nyɛ̀ bwɛm ɛ̀bɛ̀ɛ̀.",
    direction: "EN → KY",
    date: "2026-06-21",
    time: "09:45",
    type: "speech" as const,
  },
  {
    id: "h_004",
    source: "Thank you very much for your kindness.",
    target: "Asante bɛdɛ ɛ̀yɛ̀ bɔ̀kɛ mɛ̀.",
    direction: "EN → KY",
    date: "2026-06-20",
    time: "16:20",
    type: "text" as const,
  },
  {
    id: "h_005",
    source: "Ɛndiŋ jɛ àm Kennedy, mɛ kɛ Cameroon.",
    target: "My name is Kennedy, I am from Cameroon.",
    direction: "KY → EN",
    date: "2026-06-20",
    time: "11:08",
    type: "text" as const,
  },
  {
    id: "h_006",
    source: "The children are playing in the field.",
    target: "Àbɛ̀ nɔŋ ɛ dɛ kɛ wɔ bɔ̀kɛ ɛ̀tɛ̀mɛ̀.",
    direction: "EN → KY",
    date: "2026-06-20",
    time: "08:55",
    type: "speech" as const,
  },
  {
    id: "h_007",
    source: "I love learning new languages every day.",
    target: "Mɛ ya̧ɛ mɛ̀nɛ bɔ̀kɛ àkɛ̀ ndɛm wɔ nyɔŋ.",
    direction: "EN → KY",
    date: "2026-06-19",
    time: "19:30",
    type: "text" as const,
  },
  {
    id: "h_008",
    source: "Wɔ nyɔŋ ɛ dɛ ya̧ɛ bɔ̀kɛ ɛ̀tɛ.",
    target: "Today the weather is very beautiful.",
    direction: "KY → EN",
    date: "2026-06-19",
    time: "07:15",
    type: "text" as const,
  },
  {
    id: "h_009",
    source: "Where is the nearest hospital from here?",
    target: "Spital ɛ̀ dɛ yɛ̀ bɔ̀ wɔ nɛm?",
    direction: "EN → KY",
    date: "2026-06-18",
    time: "14:00",
    type: "speech" as const,
  },
  {
    id: "h_010",
    source: "Our culture and language are our identity.",
    target: "Àkɛ̀ bwɛm àkwɛ̀ bɔ̀kɛ jɛ àkɛ̀ ndɛm ɛ̀.",
    direction: "EN → KY",
    date: "2026-06-18",
    time: "10:22",
    type: "text" as const,
  },
];

export const quickTranslations = [
  { en: "Hello", ky: "Ɛyo̧" },
  { en: "Thank you", ky: "Asante" },
  { en: "Good morning", ky: "Mbɛ̀ wɔ nyɔŋ" },
  { en: "How are you?", ky: "O̧ ndɛ mɛ?" },
  { en: "My name is…", ky: "Ɛndiŋ jɛ…" },
  { en: "Please", ky: "Mbok" },
];

export const dashboardStats = [
  { label: "Total Translations", value: 247, change: "+12%", icon: "globe", color: "#012D5A" },
  { label: "Text Translations", value: 189, change: "+8%", icon: "type", color: "#0369a1" },
  { label: "Speech Translations", value: 58, change: "+23%", icon: "mic", color: "#F07814" },
  { label: "This Week", value: 34, change: "+5%", icon: "calendar", color: "#059669" },
];
